baseurl = "https://lai9fox.github.io/blog/"
languageCode = "zh-cn"
theme = "hugo-theme-stack"
paginate = 10
title = "狐假虎威"
# disqusShortname = "hugo-theme-stack"
DefaultContentLanguage = "zh-cn"
hasCJKLanguage = true

[permalinks]
# post = "/post/:year/:month/:slug/"
page = "/:slug/"

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true
favicon = "/favicon.ico"

  [params.footer]
  since = 2023

  [params.dateFormat]
  published = "Jan 02, 2006"
  lastUpdated = "Jan 02, 2006 15:04 MST"

  [params.sidebar]
  subtitle = "Haste makes waste."

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = "img/avatar.png"

  [params.article]
  math = false
  toc = true
  readingTime = true

    [params.article.license]
    enabled = true
    default = "Licensed under CC BY-NC-SA 4.0"

  [params.comments]
  enabled = true
  provider = "gitalk"
    [params.comments.gitalk]
      owner = 'lai9fox'
      admin = ['lai9fox']
      repo = 'https://github.com/lai9fox/blog'
      clientID = '0c60543304dc769dd02e'
      clientSecret = '170ec2b71f73b5785e9b759df22efd48663721e5'

  #   [params.comments.disqusjs]

  #   [params.comments.utterances]
  #   issueTerm = "pathname"

  #   [params.comments.remark42]

  #   [params.comments.vssue]
  #   autoCreateIssue = false

  #   [params.comments.waline]
  #   emoji = [ "https://unpkg.com/@waline/emojis@1.0.1/weibo" ]
  #   requiredMeta = [ "name", "email", "url" ]

  #     [params.comments.waline.locale]
  #     admin = "Admin"

  #   [params.comments.twikoo]

  #   [params.comments.cactus]
  #   defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
  #   serverName = "cactus.chat"
  #   siteName = ""

  #   [params.comments.giscus]
  #   reactionsEnabled = 1
  #   emitMetadata = 0

  #   [params.comments.gitalk]

  #   [params.comments.cusdis]

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.homepage]]
type = "categories"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

  [params.widgets.homepage.params]
  limit = 10

[[params.widgets.page]]
type = "toc"

# [params.opengraph.twitter]
# card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

[params.colorScheme]
toggle = true
default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

[menu]
main = [ ]

  [[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/lai9fox"

    [menu.social.params]
    icon = "brand-github"

  # [[menu.social]]
  # identifier = "email"
  # name = "Email"
  # url = "mailto:1591765125@qq.com"

  #   [menu.social.params]
  #   icon = "brand-email"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.goldmark.renderer]
unsafe = false

[markup.goldmark.extensions]
typographer = false

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 2
